language: c

os:
  - linux
  - osx
  - windows

addons:
  coverity_scan:
    project:
      name: "fennecdjay/Gwion"
      description: "strongly-timed musical programming language"
    notification_email: astor.jeremie@wanadoo.fr
    build_command: make
    branch_pattern: coverity_scan

env:
  global:
  - CC_TEST_REPORTER_ID=1ef7168aff2b8902922b345c8b1b9be3fd2442fa4f2096634b42235bcbaa2c47
  - export CICFLAGS="-Wno-attributes -Wno-unknown-pragmas"
  - GWION_ADD_DIR=$TRAVIS_BUILD_DIR/add
  - GWION_TEST_DIR=$TRAVIS_BUILD_DIR/tmp_test
  - PREFIX=$TRAVIS_BUILD_DIR
  - USE_MEMCHECK=1
  - secure: qC1iGXWyzrJrn6pIxZup0CYThjZC44NuEStU50wx3Jdi1owYkkQ/eXWw55TvhswmnnO7l+wQsN2RnP6zsjJTq6wuNjAyG8w89rgCevbCpOu5vZAWF0+/c5H7qDG+NS9aumfd53QPC55ZcjjjM+5j71+J8XXoj+n4ygR5dVtTk/xF4sTBBwyaUkG9r/Hoocd3gtd3Up/ZlDYQd5/tCrfiFcWvAs4197LPfCDIW7k/tnXEmKV3le/yTXU0/ZByzjGQkhhpqvMqh3BTQrKExxeBt8utqnwLVwUAIWnACUIJz8bjyWWX++DwP1cFExAUBWB21A4i/qpXAieu7whcwE/hPkrVJjqEedbXNonyFHAwwOVhPIckk2OVzD6tCNp8IJZkccq8ONbqM/WpPAKip//13wttDvsDRgva2nkS7LZ6n/V1MHye6OgZD3778bty6YGOSkyEiT9ryZGaDrGbNbdXcAyCUmbd8a/N1RnQC+TSkvRBAhVL50dgSHNYNXZNn02hqiD/QNDqgdjOQ/jkgROQxMj8EnsVDPTOWIYkKpiTawQF9WqCPdQLl7+P5+uuUhfeMiyohu90yDOl7BXxhS8FJt/YUCMBLGS3OsmnVpA5XoG2aBZKDz1gXedNcQJ1JAEB0XO5mSJn4jXbDtI9QMZu/jNxm1TmyJaItv1l0ln3zn0=
  matrix:
  - USE_DOUBLE=1
  - USE_DOUBLE=0

matrix:
  allow_failures:
   - os: windows

compiler:
  - gcc
  - clang

install:
  - export VALGRIND="NO_VALGRIND";
    export SEVERITY=3;
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then
      pip install --user --upgrade pip;
      pip install --user urllib3[secure];
      pip install --user cpp-coveralls;
    fi;
  - if [ $(uname) != "Linux" ] && [ $(uname) != "Darwin" ]; then 
      export BUILD_ON_WINDOWS=1;
      choco install make;
      if [ $(CC) = "gcc" ];
      then export LDFLAGS="$LDLAGS -lpsapi -shared -fPIC -Wl,--export-all -Wl,--enable-auto-import";
      else export LDFLAGS="$LDLAGS -lpsapi -shared -fPIC";
      fi;
      export LIBS="$LIBS -lpsapi -shared -fPIC";
    fi;

before_script:
  - git submodule update --init util ast;
  - if [ $(uname) = "Darwin" ]; then export SEVERITY=1; fi;
  - mkdir -p "$GWION_ADD_DIR" "$GWION_TEST_DIR"

script:
  - if [ $(uname) = "Linux" ] || [ $(uname) = "Darwin" ]; then
      if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ];
      then cd util && make && cd ../ast && make && cd .. && USE_COVERAGE=1 make && make test;
      else make && make test;
      fi
    else {
      if [ "$CC" = "clang" ];
      then export CFLAGS+=" -D_USE_MATH_DEFINES -D_CRT_SECURE_NO_WARNINGS -Dssize_t=SSIZE_T";
      fi;
      make.exe && make.exe test;
    }
    fi;

after_success:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then
      COVERALLS_REPO_TOKEN=OdYyiJMdUIolVNqWHX5pe3QERNcBv7t2p coveralls -i include -i src/ --gcov-options '\-lp' -b.;
    fi

after_failure:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.7  ]; then
      make clean; DEBUG_STACK=1 make;
      ./gwion tests/tree/array_test.gw;
    fi

git:
  submodules: false
