
name: Update Bot

on:
  push:
    branches:    
    - 'master'

jobs:
  build:
    name: Push to bot repo
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Clone and push
      run: |
        git clone https://github.com/Gwion/gwion-cinch-bot
        cd gwion-cinch-bot
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit --allow-empty -m "update gwion"
        git remote set-url origin https://${{ secrets.GWION_BOT }}@github.com/Gwion/gwion-cinch-bot.git
        git push
