name: CI

on:
  [push, workflow_dispatch, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
    - uses: actions/checkout@v1
      name: Checkout
    - uses: actions/setup-python@v1
      name: Setup Python
    - uses: actions/setup-ruby@v1
      name: Setup Ruby

    - name: Dependencies
      run: bash scripts/update.sh

    - name: MdBook
      uses: peaceiris/actions-mdbook@v1
      with:                                                                                                                                                                                 
         mdbook-version: 'latest'

    - name: GIT things
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Get benchmarks
      run: |
        git submodule update --init gwion-benchmark
        cd gwion-benchmark
        git pull origin results

    - name: Build book
      run: PATH=$PWD:$PATH make build

    - name: Push book
      run: |
        git add -f book
        git commit -m "add book"
        git remote set-url origin https://${{ secrets.GWION_TOKEN }}@github.com/Gwion/Gwion.git
        git push origin :gh-pages || true
        git subtree push --prefix book origin gh-pages
